spring.application.name=professy

# MySQL Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/professy_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=@Mysql0707
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=greatley-poshley-jwt-secret-key-2026-123456
jwt.expiration=86400000